-- Temporarily at home in the use_item.lua blueprint "item_ward_dispenser" usable check
-- Important code is in lib_analytics/vangtage.lua (named as so because it automates finding and resolving ward locations by building >terrain height levels< aggregate objects and confirming valid via GetCurrentActionType failures to ward)
