abaddon
alchemist
ancient_apparition
anti-mage
axe
bane
beastmaster
bloodseeker
bounty_hunter
brewmaster
broodmother
centaur_warrunner
chaos_knight
chen
clinkz
clockwerk
crystal_maiden
dark_seer
dawnbreaker
disruptor
doom
dragon_knight
earth_spirit
elder_titan
enchantress
enigma
grimstroke
gyrocopter
huskar
invoker
jakiro
juggernaut
kunkka
legion_commander
leshrac
lina
lone_druid
luna
lycan
medusa
mirana
monkey_king
naga_siren
necrophos
night_stalker
nyx_assassin
ogre_magi
omniknight
outworld_destroyer
phantom_lancer
primal_beast
pugna
queen_of_pain
razor
riki
sand_king
shadow_demon
shadow_shaman
silencer
skywrath_mage
slardar
snapfire
spectre
spirit_breaker
sven
techies
tidehunter
timbersaw
tinker
tiny
treant_protector
troll_warlord
underlord
undying
ursa
vengeful_spirit
venomancer
viper
visage
warlock
weaver
winter_wyvern
witch_doctor
wraith_king
zeus
0.6
arc_warden
dark_willow
dazzle
drow_ranger
io
keeper_of_the_light
lich
meepo
morphling
muerta
oracle
pudge
rubick
slark
sniper
templar_assassin
tusk
void_spirit
0.7
death_prophet
ember_spirit
lion
magnus
mars
phantom_assassin
storm_spirit
terrorblade
windranger
</td>
<td>0.8
</td></tr>
<tr>
<td><a href="/wiki/batrider" title="batrider"><img alt="batrider minimap icon.png" src="data:image/gif;base64,r0lgodlhaqabaiabaaaaap///yh5baeaaaealaaaaaabaaeaqaictaeaow%3d%3d" decoding="async" loading="lazy" width="32" height="32" class="pixelart lazyload" data-image-name="batrider minimap icon.png" data-image-key="batrider_minimap_icon.png" data-src="https://static.wikia.nocookie.net/dota2_gamepedia/images/0/0d/batrider_minimap_icon.png/revision/latest?cb=20120717000918" /></a><a href="/wiki/bristleback" title="bristleback"><img alt="bristleback minimap icon.png" src="data:image/gif;base64,r0lgodlhaqabaiabaaaaap///yh5baeaaaealaaaaaabaaeaqaictaeaow%3d%3d" decoding="async" loading="lazy" width="32" height="32" class="pixelart lazyload" data-image-name="bristleback minimap icon.png" data-image-key="bristleback_minimap_icon.png" data-src="https://static.wikia.nocookie.net/dota2_gamepedia/images/a/a8/bristleback_minimap_icon.png/revision/latest?cb=20130329040753" /></a><a href="/wiki/earthshaker" title="earthshaker"><img alt="earthshaker minimap icon.png" src="data:image/gif;base64,r0lgodlhaqabaiabaaaaap///yh5baeaaaealaaaaaabaaeaqaictaeaow%3d%3d" decoding="async" loading="lazy" width="32" height="32" class="pixelart lazyload" data-image-name="earthshaker minimap icon.png" data-image-key="earthshaker_minimap_icon.png" data-src="https://static.wikia.nocookie.net/dota2_gamepedia/images/4/42/earthshaker_minimap_icon.png/revision/latest?cb=20120717000934" /></a><a href="/wiki/faceless_void" title="faceless void"><img alt="faceless void minimap icon.png" src="data:image/gif;base64,r0lgodlhaqabaiabaaaaap///yh5baeaaaealaaaaaabaaeaqaictaeaow%3d%3d" decoding="async" loading="lazy" width="32" height="32" class="pixelart lazyload" data-image-name="faceless void minimap icon.png" data-image-key="faceless_void_minimap_icon.png" data-src="https://static.wikia.nocookie.net/dota2_gamepedia/images/8/8e/faceless_void_minimap_icon.png/revision/latest?cb=20150321000709" /></a><a href="/wiki/hoodwink" title="hoodwink"><img alt="hoodwink minimap icon.png" src="data:image/gif;base64,r0lgodlhaqabaiabaaaaap///yh5baeaaaealaaaaaabaaeaqaictaeaow%3d%3d" decoding="async" loading="lazy" width="32" height="32" class="pixelart lazyload" data-image-name="hoodwink minimap icon.png" data-image-key="hoodwink_minimap_icon.png" data-src="https://static.wikia.nocookie.net/dota2_gamepedia/images/d/d0/hoodwink_minimap_icon.png/revision/latest?cb=20201217233800" /></a><a href="/wiki/lifestealer" title="lifestealer"><img alt="lifestealer minimap icon.png" src="data:image/gif;base64,r0lgodlhaqabaiabaaaaap///yh5baeaaaealaaaaaabaaeaqaictaeaow%3d%3d" decoding="async" loading="lazy" width="32" height="32" class="pixelart lazyload" data-image-name="lifestealer minimap icon.png" data-image-key="lifestealer_minimap_icon.png" data-src="https://static.wikia.nocookie.net/dota2_gamepedia/images/7/74/lifestealer_minimap_icon.png/revision/latest?cb=20120717000943" /></a><a href="/wiki/marci" title="marci"><img alt="marci minimap icon.png" src="data:image/gif;base64,r0lgodlhaqabaiabaaaaap///yh5baeaaaealaaaaaabaaeaqaictaeaow%3d%3d" decoding="async" loading="lazy" width="32" height="32" class="pixelart lazyload" data-image-name="marci minimap icon.png" data-image-key="marci_minimap_icon.png" data-src="https://static.wikia.nocookie.net/dota2_gamepedia/images/f/ff/marci_minimap_icon.png/revision/latest?cb=20211029112022" /></a><a href="/wiki/nature%27s_prophet" title="nature&#39;s prophet"><img alt="nature&#39;s prophet minimap icon.png" src="data:image/gif;base64,r0lgodlhaqabaiabaaaaap///yh5baeaaaealaaaaaabaaeaqaictaeaow%3d%3d" decoding="async" loading="lazy" width="32" height="32" class="pixelart lazyload" data-image-name="nature&#39;s prophet minimap icon.png" data-image-key="nature%27s_prophet_minimap_icon.png" data-src="https://static.wikia.nocookie.net/dota2_gamepedia/images/a/a4/nature%27s_prophet_minimap_icon.png/revision/latest?cb=20120717000951" /></a><a href="/wiki/pangolier" title="pangolier"><img alt="pangolier minimap icon.png" src="data:image/gif;base64,r0lgodlhaqabaiabaaaaap///yh5baeaaaealaaaaaabaaeaqaictaeaow%3d%3d" decoding="async" loading="lazy" width="32" height="32" class="pixelart lazyload" data-image-name="pangolier minimap icon.png" data-image-key="pangolier_minimap_icon.png" data-src="https://static.wikia.nocookie.net/dota2_gamepedia/images/8/80/pangolier_minimap_icon.png/revision/latest?cb=20171030210811" /></a><a href="/wiki/phoenix" title="phoenix"><img alt="phoenix minimap icon.png" src="data:image/gif;base64,r0lgodlhaqabaiabaaaaap///yh5baeaaaealaaaaaabaaeaqaictaeaow%3d%3d" decoding="async" loading="lazy" width="32" height="32" class="pixelart lazyload" data-image-name="phoenix minimap icon.png" data-image-key="phoenix_minimap_icon.png" data-src="https://static.wikia.nocookie.net/dota2_gamepedia/images/2/21/phoenix_minimap_icon.png/revision/latest?cb=20140130195654" /></a><a href="/wiki/puck" title="puck"><img alt="puck minimap icon.png" src="data:image/gif;base64,r0lgodlhaqabaiabaaaaap///yh5baeaaaealaaaaaabaaeaqaictaeaow%3d%3d" decoding="async" loading="lazy" width="32" height="32" class="pixelart lazyload" data-image-name="puck minimap icon.png" data-image-key="puck_minimap_icon.png" data-src="https://static.wikia.nocookie.net/dota2_gamepedia/images/c/cf/puck_minimap_icon.png/revision/latest?cb=20130613050809" /></a><a href="/wiki/shadow_fiend" title="shadow fiend"><img alt="shadow fiend minimap icon.png" src="data:image/gif;base64,r0lgodlhaqabaiabaaaaap///yh5baeaaaealaaaaaabaaeaqaictaeaow%3d%3d" decoding="async" loading="lazy" width="32" height="32" class="pixelart lazyload" data-image-name="shadow fiend minimap icon.png" data-image-key="shadow_fiend_minimap_icon.png" data-src="https://static.wikia.nocookie.net/dota2_gamepedia/images/0/00/shadow_fiend_minimap_icon.png/revision/latest?cb=20140924021543" /></a>
</td>
<td>0.9
</td></tr>
</tbody></table>
<table class="wikitable collapsible mw-datatable" width="100%;" style="text-align:center;">
